bokeItem/views/login.py
from flask import Blueprint,Flask, render_template, request, redirect, url_for, session, g
from flask_sqlalchemy import SQLAlchemy
import time
from app import User,db,Article,Comment
login = Blueprint('login',__name__)
import hashlib

# 登录首页
@login.route('/',methods = [ 'GET','POST'] )
def login_index():
    if request.method == 'GET':
        return render_template('login_register/login.html')
    else:
        telephone = request.form.get('login-telephone')
        password = request.form.get('login-password')
        #对用户输入的密码进行加密
        hash = hashlib.md5(bytes('9385',encoding='utf-8'))#md5对象，md5不能反解，但是加密是固定的，就是关系是一一对应，所以有缺陷，可以被对撞出来
        hash.update(bytes(password,encoding='utf-8'))#要对哪个字符串进行加密，就放这里
        password = hash.hexdigest()
        #验证
        vcode= request.form.get('vcode')
        print(vcode)
        user = User.query.filter(User.telephone==telephone).first()
        if user and user.password==password:
            session['user_id'] = user.id
            session.permanent = True
            return redirect(url_for('boke'))
        else:
            # return redirect(url_for('login.login_index'))
            return render_template('login_register/login.1.html')

# 管理员登录页
@login.route('/login_gl',methods=['GET','POST'])
def login_gl_index():
    if request.method == 'GET':
        return render_template('login_register/login_gl.html')
    else:
        username = request.form.get('username')
        password = request.form.get('pw')
        #对用户输入的密码进行加密
        # md5对象，md5不能反解，但是加密是固定的，就是关系是一一对应，所以有缺陷，可以被对撞出来
        hash = hashlib.md5(bytes('9385', encoding='utf-8'))
        hash.update(bytes(password, encoding='utf-8'))  # 要对哪个字符串进行加密，就放这里
        password = hash.hexdigest()
        
        user = User.query.filter(User.id==1).first()        
        if user and user.password==password:
                session['user_id'] = user.id
                session.permanent = True
                return render_template('X-admin/index.html',user=user)
        else:
            return render_template('login_register/login_gl.html')
# 欢迎首页
@login.route('/welcome.html',methods=['GET','POST'])
def welcome():
    users = User.query.filter(User.id!=1).all()  
    articles = Article.query.filter().all()
    comments = Comment.query.filter().all()
    readcount = 0
    agreecount = 0
    for article in articles:
        readcount += article.readcount
        agreecount += article.agreecount
    return render_template('X-admin/welcome.html',users=users,articles=articles,comments=comments,readcount=readcount,agreecount=agreecount) 

# 成员列表页
@login.route('/member-list.html',methods=['GET','POST'])
def member_list():
    users = User.query.filter(User.id!=1).all()
    return render_template('X-admin/member-list.html',users=users) 

# 删除成员
@login.route('/member-list.html/<user_id>') 
def member_list_del(user_id):
    delete_users = User.query.filter(User.id==user_id).first()
    delete_users.online = 1
    db.session.add(delete_users)
    db.session.commit()
    time.sleep(2)
    return redirect(url_for('login.member_list'))   
# 恢复成员
@login.route('/member-del.html/<user_id>') 
def member_list_huihu(user_id):
    delete_users = User.query.filter(User.id==user_id).first()
    delete_users.online = 0
    db.session.add(delete_users)
    db.session.commit()
    time.sleep(2)
    return redirect(url_for('login.member_del'))

# 成员恢复页
@login.route('/member-del.html',methods=['GET','POST'])
def member_del():
    users = User.query.filter(User.id!=1).all()
    return render_template('X-admin/member-del.html',users=users) 

# 文章列表页
@login.route('/article-list.html',methods=['GET','POST'])
def article_list():
    articles = Article.query.filter().all()
    return render_template('X-admin/article-list.html',articles=articles)

# 删除文章
@login.route('/article-list.html/<article_id>') 
def article_list_del(article_id):
    delete_articles = Article.query.filter(Article.id==article_id).first()
    delete_articles.isexit = 1
    db.session.add(delete_articles)
    db.session.commit()
    time.sleep(2)
    return redirect(url_for('login.article_list'))
# 文章恢复
@login.route('/article-del.html/<article_id>') 
def article_del_huihu(article_id):
    delete_articles = Article.query.filter(Article.id==article_id).first()
    delete_articles.isexit = 0
    db.session.add(delete_articles)
    db.session.commit()
    time.sleep(2)
    return redirect(url_for('login.article_del'))

# 文章恢复页
@login.route('/article-del.html',methods=['GET','POST'])
def article_del():
    articles = Article.query.filter().all()
    return render_template('X-admin/article-del.html',articles=articles) 

# 评论页
@login.route('/order-list.html',methods=['GET','POST'])
def order_list():
    comments = Comment.query.filter().all()
    return render_template('X-admin/order-list.html',comments=comments) 
# 分类页
@login.route('/cate.html',methods=['GET','POST'])
def cate():
    articles = Article.query.filter().all()
    return render_template('X-admin/cate.html',articles=articles) 

# 审核页
@login.route('/check-list.html',methods=['GET','POST'])
def check_article():
    articles = Article.query.filter().all()
    return render_template('X-admin/check-list.html',articles=articles)
# 审核文章通过
@login.route('/check-list.html/<article_id>') 
def article_list_check(article_id):
    delete_articles = Article.query.filter(Article.id==article_id).first()
    delete_articles.isexit = 0
    db.session.add(delete_articles)
    db.session.commit()
    time.sleep(2)
    return redirect(url_for('login.check_article'))


# 注销跳转登录页
@login.route('/logout')
def logout():
    # session.pop('user_id')
    # del session['user_id']
    session.clear()
    return redirect(url_for('login.login_index'))

bokeItem/templates/X-admin/article-del.html
<!DOCTYPE html>
<html>
  
  <head>
    <meta charset="UTF-8">
    <title>文章删除页面</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="../../static/X-admin/css/font.css">
    <link rel="stylesheet" href="../../static/X-admin/css/xadmin.css">
    <script type="text/javascript" src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script src="../../static/X-admin/lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="../../static/X-admin/js/xadmin.js"></script>
    <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
    <!--[if lt IE 9]>
      <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
      <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  
  <body class="layui-anim layui-anim-up">
    <div class="x-nav">
      <span class="layui-breadcrumb">
        <a href="">首页</a>
        <a href="">演示</a>
        <a>
          <cite>导航元素</cite></a>
      </span>
      <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right" href="javascript:location.replace(location.href);" title="刷新">
        <i class="layui-icon" style="line-height:30px">ဂ</i></a>
    </div>
    <div class="x-body">
      <div class="layui-row">
        <form class="layui-form layui-col-md12 x-so">
          <!-- <input class="layui-input" placeholder="开始日" name="start" id="start">
          <input class="layui-input" placeholder="截止日" name="end" id="end"> -->
          <input type="text" name="username"  placeholder="请输入文章" autocomplete="off" class="layui-input">
          <button class="layui-btn"  lay-submit="" lay-filter="sreach"><i class="layui-icon">&#xe615;</i></button>
        </form>
      </div>
      <xblock>
        <button class="layui-btn layui-btn-danger" onclick="delAll()"><i class="layui-icon"></i>批量恢复</button>
        <button class="layui-btn" onclick="x_admin_show('添加用户','./member-add.html',600,400)"><i class="layui-icon"></i>添加</button>
        <span class="x-right" style="line-height:40px">共有数据：{{articles.__len__()}} 条</span>
      </xblock>
      <table class="layui-table">
          <thead>
              <tr>
                <th>
                  <div class="layui-unselect header layui-form-checkbox" lay-skin="primary"><i class="layui-icon">&#xe605;</i></div>
                </th>
                <th>ID</th>
                <th>文章标题</th>
                <th>作者</th>
                <!-- <th>内容</th> -->
                <th>类型</th>
                <th>评论数</th>
                <th>阅读量</th>
                <th>点赞数</th>
                <th>加入时间</th>
                <th>操作</th></tr>
            </thead>
        <tbody>
            {%for article in articles%}
            {%if article.isexit==1%}
            <tr>
              <td>
                <div class="layui-unselect layui-form-checkbox" lay-skin="primary" data-id='2'><i class="layui-icon">&#xe605;</i></div>
              </td>
              <td>{{article.id}}</td>
              <td>{{article.title}}</td>
              <td>{{article.user.username}}</td>
              <!-- <td>{{article.content}}</td> -->
              <td>{{article.types}}</td>
              <td>{{article.comments.__len__()}}</td>
              <td>{{article.readcount}}</td>
              <td>{{article.agreecount}}</td>
              <td>{{article.time}}</td>          
              <td class="td-manage">
                <!-- <a onclick="member_stop(this,'10001')" href="javascript:;"  title="启用">
                  <i class="layui-icon">&#xe601;</i>
                </a>
                <a title="编辑"  onclick="x_admin_show('编辑','member-edit.html',600,400)" href="javascript:;">
                  <i class="layui-icon">&#xe642;</i>
                </a>
                <a onclick="x_admin_show('修改密码','member-password.html',600,400)" title="修改密码" href="javascript:;">
                  <i class="layui-icon">&#xe631;</i>
                </a> -->
                <a title="恢复" onclick="member_del(this,'要删除的id')" href="{{url_for('login.article_del_huihu',article_id=article.id)}}">
                  <i class="layui-icon">&#xe601;</i>
                </a>
              </td>
            </tr>
            {%endif%}
            {%endfor%}
        </tbody>
      </table>
      <!-- <div class="page">
        <div>
          <a class="prev" href="">&lt;&lt;</a>
          <a class="num" href="">1</a>
          <span class="current">2</span>
          <a class="num" href="">3</a>
          <a class="num" href="">489</a>
          <a class="next" href="">&gt;&gt;</a>
        </div>
      </div> -->

    </div>
    <script>
      layui.use('laydate', function(){
        var laydate = layui.laydate;
        
        //执行一个laydate实例
        laydate.render({
          elem: '#start' //指定元素
        });

        //执行一个laydate实例
        laydate.render({
          elem: '#end' //指定元素
        });
      });

       /*用户-停用*/
      function member_stop(obj,id){
          layer.confirm('确认要停用吗？',function(index){

              if($(obj).attr('title')=='启用'){

                //发异步把用户状态进行更改
                $(obj).attr('title','停用')
                $(obj).find('i').html('&#xe62f;');

                $(obj).parents("tr").find(".td-status").find('span').addClass('layui-btn-disabled').html('已停用');
                layer.msg('已停用!',{icon: 5,time:1000});

              }else{
                $(obj).attr('title','启用')
                $(obj).find('i').html('&#xe601;');

                $(obj).parents("tr").find(".td-status").find('span').removeClass('layui-btn-disabled').html('已启用');
                layer.msg('已启用!',{icon: 5,time:1000});
              }
              
          });
      }

      /*用户-删除*/
      function member_del(obj,id){
          layer.confirm('确认要恢复吗？',function(index){
              //发异步删除数据
              $(obj).parents("tr").remove();
              layer.msg('已恢复!',{icon:1,time:1000});
          });
      }



      function delAll (argument) {

        var data = tableCheck.getData();
  
        layer.confirm('确认要恢复吗？'+data,function(index){
            //捉到所有被选中的，发异步进行删除
            layer.msg('恢复成功', {icon: 1});
            $(".layui-form-checked").not('.header').parents('tr').remove();
        });
      }
    </script>
    <script>var _hmt = _hmt || []; (function() {
        var hm = document.createElement("script");
        hm.src = "https://hm.baidu.com/hm.js?b393d153aeb26b46e9431fabaf0f6190";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);
      })();</script>
  </body>

</html>

bokeItem/templates/X-admin/article-list.html
<!DOCTYPE html>
<html>
  
  <head>
    <meta charset="UTF-8">
    <title>文章页面</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="../../static/X-admin/css/font.css">
    <link rel="stylesheet" href="../../static/X-admin/css/xadmin.css">
    <script type="text/javascript" src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script src="../../static/X-admin/lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="../../static/X-admin/js/xadmin.js"></script>
    <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
    <!--[if lt IE 9]>
      <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
      <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  
  <body class="layui-anim layui-anim-up">
    <div class="x-nav">
      <span class="layui-breadcrumb">
        <a href="">首页</a>
        <a href="">演示</a>
        <a>
          <cite>导航元素</cite></a>
      </span>
      <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right" href="javascript:location.replace(location.href);" title="刷新">
        <i class="layui-icon" style="line-height:30px">ဂ</i></a>
    </div>
    <div class="x-body">
      <div class="layui-row">
        <form class="layui-form layui-col-md12 x-so">
          <!-- <input class="layui-input" placeholder="开始日" name="start" id="start">
          <input class="layui-input" placeholder="截止日" name="end" id="end"> -->
          <input type="text" name="username"  placeholder="请输入你搜索文章" autocomplete="off" class="layui-input">
          <button class="layui-btn"  lay-submit="" lay-filter="sreach"><i class="layui-icon">&#xe615;</i></button>
        </form>
      </div>
      <xblock>
        <button class="layui-btn layui-btn-danger" onclick="delAll()"><i class="layui-icon"></i>批量删除</button>
        <button class="layui-btn" onclick="x_admin_show('添加用户','./member-add.html',600,400)"><i class="layui-icon"></i>添加</button>
        <span class="x-right" style="line-height:40px">共有数据：{{articles.__len__()}} 条</span>
      </xblock>
      <table class="layui-table">
        <thead>
          <tr>
            <th>
              <div class="layui-unselect header layui-form-checkbox" lay-skin="primary"><i class="layui-icon">&#xe605;</i></div>
            </th>
            <th>ID</th>
            <th>文章标题</th>
            <th>作者</th>
            <!-- <th>内容</th> -->
            <th>类型</th>
            <th>评论数</th>
            <th>阅读量</th>
            <th>点赞数</th>
            <th>加入时间</th>
            <th>操作</th></tr>
        </thead>
        <tbody>
          {%for article in articles%}
          {%if article.isexit==0%}
          <tr>
            <td>
              <div class="layui-unselect layui-form-checkbox" lay-skin="primary" data-id='2'><i class="layui-icon">&#xe605;</i></div>
            </td>
            <td>{{article.id}}</td>
            <td>{{article.title}}</td>
            <td>{{article.user.username}}</td>
            <!-- <td>{{article.content}}</td> -->
            <td>{{article.types}}</td>
            <td>{{article.comments.__len__()}}</td>
            <td>{{article.readcount}}</td>
            <td>{{article.agreecount}}</td>
            <td>{{article.time}}</td>          
            <td class="td-manage">
              <!-- <a onclick="member_stop(this,'10001')" href="javascript:;"  title="启用">
                <i class="layui-icon">&#xe601;</i>
              </a>
              <a title="编辑"  onclick="x_admin_show('编辑','member-edit.html',600,400)" href="javascript:;">
                <i class="layui-icon">&#xe642;</i>
              </a>
              <a onclick="x_admin_show('修改密码','member-password.html',600,400)" title="修改密码" href="javascript:;">
                <i class="layui-icon">&#xe631;</i>
              </a> -->
              <a title="删除" onclick="member_del(this,'要删除的id')" href="{{url_for('login.article_list_del',article_id=article.id)}}">
                <i class="layui-icon">&#xe640;</i>
              </a>
            </td>
          </tr>
          {%endif%}
          {%endfor%}
        </tbody>
      </table>
      <!-- <div class="page">
        <div>
          <a class="prev" href="">&lt;&lt;</a>
          <a class="num" href="">1</a>
          <span class="current">2</span>
          <a class="num" href="">3</a>
          <a class="num" href="">489</a>
          <a class="next" href="">&gt;&gt;</a>
        </div>
      </div> -->

    </div>
    <script>
      layui.use('laydate', function(){
        var laydate = layui.laydate;
        
        //执行一个laydate实例
        laydate.render({
          elem: '#start' //指定元素
        });

        //执行一个laydate实例
        laydate.render({
          elem: '#end' //指定元素
        });
      });

       /*用户-停用*/
      function member_stop(obj,id){
          layer.confirm('确认要停用吗？',function(index){

              if($(obj).attr('title')=='启用'){

                //发异步把用户状态进行更改
                $(obj).attr('title','停用')
                $(obj).find('i').html('&#xe62f;');

                $(obj).parents("tr").find(".td-status").find('span').addClass('layui-btn-disabled').html('已停用');
                layer.msg('已停用!',{icon: 5,time:1000});

              }else{
                $(obj).attr('title','启用')
                $(obj).find('i').html('&#xe601;');

                $(obj).parents("tr").find(".td-status").find('span').removeClass('layui-btn-disabled').html('已启用');
                layer.msg('已启用!',{icon: 5,time:1000});
              }
              
          });
      }

      /*用户-删除*/
      function member_del(obj,id){
          layer.confirm('确认要删除吗？',function(index){
              //发异步删除数据
              $(obj).parents("tr").remove();
              layer.msg('已删除!',{icon:1,time:10});
          });
      }



      function delAll (argument) {

        var data = tableCheck.getData();
  
        layer.confirm('确认要删除吗？'+data,function(index){
            //捉到所有被选中的，发异步进行删除
            layer.msg('删除成功', {icon: 1});
            $(".layui-form-checked").not('.header').parents('tr').remove();
        });
      }
    </script>
    <script>var _hmt = _hmt || []; (function() {
        var hm = document.createElement("script");
        hm.src = "https://hm.baidu.com/hm.js?b393d153aeb26b46e9431fabaf0f6190";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);
      })();</script>
  </body>

</html>

bokeItem/templates/X-admin/check-list.html
<!DOCTYPE html>
<html>
  
  <head>
    <meta charset="UTF-8">
    <title>文章页面</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="../../static/X-admin/css/font.css">
    <link rel="stylesheet" href="../../static/X-admin/css/xadmin.css">
    <script type="text/javascript" src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script src="../../static/X-admin/lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="../../static/X-admin/js/xadmin.js"></script>
    <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
    <!--[if lt IE 9]>
      <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
      <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  
  <body class="layui-anim layui-anim-up">
    <div class="x-nav">
      <span class="layui-breadcrumb">
        <a href="">首页</a>
        <a href="">演示</a>
        <a>
          <cite>导航元素</cite></a>
      </span>
      <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right" href="javascript:location.replace(location.href);" title="刷新">
        <i class="layui-icon" style="line-height:30px">ဂ</i></a>
    </div>
    <div class="x-body">
      <div class="layui-row">
        <form class="layui-form layui-col-md12 x-so">
          <!-- <input class="layui-input" placeholder="开始日" name="start" id="start">
          <input class="layui-input" placeholder="截止日" name="end" id="end"> -->
          <input type="text" name="username"  placeholder="请输入你搜索文章" autocomplete="off" class="layui-input">
          <button class="layui-btn"  lay-submit="" lay-filter="sreach"><i class="layui-icon">&#xe615;</i></button>
        </form>
      </div>
      <xblock>
        <button class="layui-btn layui-btn-danger" onclick="delAll()"><i class="layui-icon"></i>批量删除</button>
        <button class="layui-btn" onclick="x_admin_show('添加用户','./member-add.html',600,400)"><i class="layui-icon"></i>添加</button>
        <!-- <span class="x-right" style="line-height:40px">共有数据：{{articles.__len__()}} 条</span> -->
      </xblock>
      <table class="layui-table">
        <thead>
          <tr>
            <th>
              <div class="layui-unselect header layui-form-checkbox" lay-skin="primary"><i class="layui-icon">&#xe605;</i></div>
            </th>
            <th>ID</th>
            <th>文章标题</th>
            <th>作者</th>
            <!-- <th>内容</th> -->
            <th>类型</th>
            <th>加入时间</th>
            <th>操作</th></tr>
        </thead>
        <tbody>
          {%for article in articles%}
          {%if article.isexit==2%}
          <tr>
            <td>
              <div class="layui-unselect layui-form-checkbox" lay-skin="primary" data-id='2'><i class="layui-icon">&#xe605;</i></div>
            </td>
            <td>{{article.id}}</td>
            <td>{{article.title}}</td>
            <td>{{article.user.username}}</td>
            <!-- <td>{{article.content}}</td> -->
            <td>{{article.types}}</td>
            <td>{{article.time}}</td>          
            <td class="td-manage">
              
              <a title="审核" onclick="member_del(this,'要删除的id')" href="{{url_for('login.article_list_check',article_id=article.id)}}">
                <i class="layui-icon">&#xe601;</i>
              </a>
            </td>
          </tr>
          {%endif%}
          {%endfor%}
        </tbody>
      </table>
      <!-- <div class="page">
        <div>
          <a class="prev" href="">&lt;&lt;</a>
          <a class="num" href="">1</a>
          <span class="current">2</span>
          <a class="num" href="">3</a>
          <a class="num" href="">489</a>
          <a class="next" href="">&gt;&gt;</a>
        </div>
      </div> -->

    </div>
    <script>
      layui.use('laydate', function(){
        var laydate = layui.laydate;
        
        //执行一个laydate实例
        laydate.render({
          elem: '#start' //指定元素
        });

        //执行一个laydate实例
        laydate.render({
          elem: '#end' //指定元素
        });
      });

       /*用户-停用*/
      function member_stop(obj,id){
          layer.confirm('确认要停用吗？',function(index){

              if($(obj).attr('title')=='启用'){

                //发异步把用户状态进行更改
                $(obj).attr('title','停用')
                $(obj).find('i').html('&#xe62f;');

                $(obj).parents("tr").find(".td-status").find('span').addClass('layui-btn-disabled').html('已停用');
                layer.msg('已停用!',{icon: 5,time:1000});

              }else{
                $(obj).attr('title','启用')
                $(obj).find('i').html('&#xe601;');

                $(obj).parents("tr").find(".td-status").find('span').removeClass('layui-btn-disabled').html('已启用');
                layer.msg('已启用!',{icon: 5,time:1000});
              }
              
          });
      }

      /*用户-删除*/
      function member_del(obj,id){
          layer.confirm('确认要审核吗？',function(index){
              //发异步删除数据
              $(obj).parents("tr").remove();
              layer.msg('已审核!',{icon:1,time:10});
          });
      }



      function delAll (argument) {

        var data = tableCheck.getData();
  
        layer.confirm('确认要审核吗？'+data,function(index){
            //捉到所有被选中的，发异步进行删除
            layer.msg('审核成功', {icon: 1});
            $(".layui-form-checked").not('.header').parents('tr').remove();
        });
      }
    </script>
    <script>var _hmt = _hmt || []; (function() {
        var hm = document.createElement("script");
        hm.src = "https://hm.baidu.com/hm.js?b393d153aeb26b46e9431fabaf0f6190";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);
      })();</script>
  </body>

</html>