bokeItem/views/details.py
from flask import Blueprint, render_template, request, redirect, url_for, session, g
from app import Article, Comment, User, db, Reply
from functools import wraps
details = Blueprint('details', __name__)
from .tts import *

# from pydub import AudioSegment

# 登录限制的装饰器


def login_required(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        # 如果登录状态，则可以执行访问
        if session.get('user_id'):
            return func(*args, **kwargs)
        else:
            # 否则直接跳转到登录页面
            return redirect(url_for('login.login_index'))
    return wrapper


# 描述详情页
@details.route('/<article_id>', methods=['GET', 'POST'])
def detail(article_id):
    article = Article.query.filter(Article.id == article_id).first()
    TEXT = article.content
    TEXTindex = len(TEXT)

    print(TEXTindex)
    if len(TEXT) > 800:
        pass
    else:
        vedio(TEXT, article_id)
    print(len(TEXT))

    article.readcount += 1
    db.session.add(article)
    db.session.commit()
    comment = Comment.query.filter(Comment.article_id == article.id).first()
    reply = Reply.query.filter(Reply.article_id == article.id).first()
    comment_count = Comment.query.filter(
        Comment.article_id == article.id).count()
    return render_template('details/article.html', article=article, comment=comment, reply=reply, comment_count=comment_count)


# 增加评论页
@details.route('/add_comoment', methods=['POST', 'GET'])
@login_required
def add_comment():
    user = g.user
    content = request.form.get('comment_content')
    article_id = request.form.get('article_id')
    comment = Comment(content=content)
    # 有两个外键，得知道这个评论的作者和这个问题
    article = Article.query.filter(Article.id == article_id).first()

    comment.user = User.query.filter(User.id == user.id).first()
    comment.article = article
    db.session.add(comment)
    db.session.commit()

    return redirect(url_for('details.detail', article_id=article_id))


@details.route('/add_reply', methods=['POST', 'GET'])
@login_required
def add_reply():
    user = g.user
    content = request.form.get('reply_content')
    comment_id = request.form.get('comment_id')
    article_id = request.form.get('article_id')
    reply = Reply(content=content)
    # 有两个外键，得知道这个评论的作者和这个问题
    comment = Comment.query.filter(Comment.id == comment_id).first()
    article = Article.query.filter(Article.id == article_id).first()
    reply.user = User.query.filter(User.id == user.id).first()
    reply.comment = comment
    reply.article = article
    db.session.add(reply)
    db.session.commit()

    return redirect(url_for('details.detail', article_id=article_id))


# 在视图函数钱执行的钩子函数

@details.before_request
def my_before_request():
    user_id = session.get('user_id')
    if user_id:
        user = User.query.filter(User.id == user_id).first()
        if user:
            g.user = user


# 可以判断显示登录状态，不登录的状态一直执行
@details.context_processor
def my_context_processor():
    if hasattr(g, 'user'):
        return {'user': g.user}
    return {}


@details.route('../')
def article_go_index():
    # return render_template('indexs/index.html')
    return redirect(url_for('boke'))

# @details.route('../admin/')


@details.route('/go_boke')
@login_required
def article_go_admin():
    return redirect(url_for('admin.admin_message'))
    # return render_template('admin/admin_message.html')


@details.route('/detail_agree/<article_id>')
@login_required
def detail_agree(article_id):
    detail_agrees = Article.query.filter(Article.id == article_id).first()
    detail_agrees.agreecount += 1
    db.session.add(detail_agrees)
    db.session.commit()
    return redirect(url_for('details.detail', article_id=detail_agrees.id))


@details.route('/article_id')
def playsound(article_id):
    article_id = article_id+'.mp3'
    song = AudioSegment.from_wav("6.wav")
    print(article_id)
    return redirect(url_for('details.detail', article_id=article_id))

bokeItem/templates/details/article.html
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <title> {{article.title}}</title>
    <meta name="keywords" content="">
    <meta name="description" content="">

    <!-- <link rel="shortcut icon" href="favicon.ico">  -->
    <link href="/static/css/details/bootstrap.min.css?v=3.3.6" rel="stylesheet">
    <!-- <link href="/static/css/font-awesome.css?v=4.4.0" rel="stylesheet"> -->
    <link rel="stylesheet" href="/static/css/details/details.css">

    <link href="/static/css/details/animate.css" rel="stylesheet">
    <link href="/static/css/details/style.css?v=4.1.0" rel="stylesheet">

</head>

<body class="gray-bg">
    <div class="gohome">
        <a class="animated bounceInUp" href="{{url_for('details.article_go_index')}}" title="返回首页">
            <img src="../../static/img/details/门 (1).png" style='width: 26px;' alt="">
        </a>
    </div>
    <div class="wrapper wrapper-content  animated fadeInRight article">
        <div class="row">
            <div class="col-lg-10 col-lg-offset-1">
                <div class="ibox">
                    <div class="ibox-content">

                        <div class="text-center article-title">
                            <h1>
                                {{article.title}}
                            </h1>
                            <h6>{{article.user.username}}</h6>
                            <h6>{{article.time}}</h6>
                            <!-- <a  href="{{url_for('details.playsound',article_id=article.id)}}"> -->
                            <!-- 自动播放autoplay='true' loop -->
                            <audio controls>
                                <source src="../../static/mp3/{{article.id}}.mp3" type="audio/mpeg">
                                <!-- <source src="happy birthday.ogg" type="audio/ogg"> -->
                                <p>This browser does not support our audio format.</p>
                            </audio>
                            <!-- </a>     -->

                        </div>
                        <p>
                            {{article.content}}
                        </p>


                        <hr>

                        <div class="row">
                            <div class="col-lg-12">

                                <h2>发表评论：</h2>
                                <form action="{{url_for('details.add_comment')}}" method="POST">
                                    <div class="form-group">
                                        <input type="text" name="comment_content" class="form-control" placeholder="请填写评论">
                                        <input type="hidden" name="article_id" value="{{article.id}}">
                                    </div>

                                    <div class="form-group" style="text-align: right ">
                                        <button class="btn btn-primary">立即评论</button>
                                    </div>
                                </form>
                                <h6>评论人数：({{comment_count}})</h6>

                                <!-- <img style='height: 40px;'  class='agree'  src="../../static/img/details/点赞.png" alt=""> -->
                                <!-- <span>(<span class="agreenum">{{article.agreecount}}</span>)</span> -->
                                <div>
                                    <a href="{{url_for('details.detail_agree',article_id=article.id)}}" class="gray">
                                        <img style='height: 40px;' class='agree' src="../../static/img/details/点赞.png"
                                            alt="">({{article.agreecount}})
                                    </a>
                                </div>


                                <div class="social-feed-box">
                                    {%for comment in article.comments%}
                                    <div class="social-feed-box">
                                        <div class="social-avatar">
                                            <a href="{{url_for('details.article_go_admin')}}" class="pull-left">
                                                <img alt="image" src="{{comment.user.img}}">
                                            </a>
                                            <div class="media-body">
                                                <a href="#">
                                                    {{comment.user.username}}
                                                </a>
                                                <small class="text-muted">{{comment.create_time}}</small>
                                            </div>
                                        </div>

                                        <div class="social-body">
                                            <p>
                                                {{comment.content}}
                                            </p>
                                        </div>

                                        <form action="{{url_for('details.add_reply')}}" method="POST">
                                            <div class="form-group" style="text-align: right ">
                                                <button class="btn btn-primary">回复</button>
                                            </div>
                                            <div class="form-group">
                                                <input type="text" name="reply_content" class="form-control"
                                                    placeholder="回复">
                                                <input type="hidden" name="comment_id" value="{{comment.id}}">
                                                <input type="hidden" name="article_id" value="{{article.id}}">
                                            </div>


                                        </form>

                                        {%for reply in comment.replys%}
                                        <div class="social-feed-box">
                                            <div class="social-avatar">
                                                <a href="{{url_for('details.article_go_admin')}}" class="pull-left"
                                                    style="margin-left: 50px;">
                                                    <img alt="image" src="{{reply.user.img}}">
                                                </a>
                                                <div class="media-body" style="margin-left: 50px;">
                                                    <a href="#">
                                                        {{reply.user.username}}
                                                    </a>
                                                    <small class="text-muted">{{reply.time}}</small>
                                                </div>
                                            </div>

                                            <div class="social-body" style="margin-left: 100px;">
                                                <p>
                                                    {{reply.content}}
                                                </p>
                                            </div>
                                        </div>
                                        {%endfor%}
                                    </div>
                                    {%endfor%}

                                </div>



                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- 全局js -->
    <script src="/static/js/details/jquery.min.js?v=2.1.4"></script>
    <script src="/static/js/details/bootstrap.min.js?v=3.3.6"></script>



    <!-- 自定义js -->
    <script src="/static/js/details/content.js?v=1.0.0"></script>
    <!-- <script>
            var agree = document.querySelector('.agree');
            var agreenum = document.querySelector('.agreenum');

            agree.onclick = function () {
                agreenum.textContent = parseInt(agreenum.textContent)+1
            }
    </script> -->

</body>

</html>