bokeItem/views/admin.py
from flask import Blueprint,render_template,request,g,session,redirect,url_for
admin = Blueprint('admin',__name__)
from app import Article,User,Comment,db
import os
from werkzeug.utils import secure_filename
# print(Article)

# 个人主页消息页
@admin.route('/')
def admin_message():
    user = g.user
    print(user.username)
    # comments = Comment.query.filter(Comment.user_id==1).all()
    # print(comments)
    return render_template('admin/admin_message.html',user=user)

# 个人文章页
@admin.route('/article')
def admin_article():
    user = g.user
    print(user)
    admin_articles = Article.query.filter(Article.user_id==user.id).order_by('-id').all()
    # print(admin_articles)
    return render_template('admin/admin_article.html',admin_articles=admin_articles,user=user)

# 删除文章
@admin.route('/admin_delete_article/<article_id>')
def admin_delete_article(article_id):
    user = g.user
    delete_articles = Article.query.filter(Article.id==article_id).first()
    # delete_comments = Comment.query.filter(Comment.article_id==delete_articles.id).all()
    # print(delete_articles,delete_comments)
    # db.session.delete(delete_articles)
    # for delete_comment in delete_comments:
    #     db.session.delete(delete_comment)
    # db.session.commit()
    delete_articles.isexit=1
    db.session.add(delete_articles)
    db.session.commit()
    return redirect(url_for('admin.admin_article'))

# 个人好友页
@admin.route('/friend')
def admin_friend():
    user=g.user
    return render_template('admin/admin_friend.html',user = user)

# 个人资料页
@admin.route('/mydata')
def mydata():
    user=g.user
    user = User.query.filter(User.id==user.id).first()
    return render_template('admin/admin_mydata.html',user=user)

# 修改个人资料
@admin.route('/editdata',methods=['GET','POST'])
def editdata():
    user = g.user
    if request.method == 'POST':
        try:
            image = request.files['image']
            username = request.form['username']
        
            user = User.query.filter(User.id==user.id).first()
            if username:
                user.username = username
                db.session.commit()
            if image:
                basepath = os.path.dirname(os.path.dirname(__file__))
                upload_path = os.path.join(basepath, 'static/img/admin/touxiang',secure_filename(image.filename))
                image.save(upload_path)
                path = ('/static/img/admin/touxiang/'+ secure_filename(image.filename))
                user.img = path
                db.session.commit()
            return render_template('admin/admin_mydata.html',user=user)
        except:
            return render_template('admin/admin_mydata.html',user=user)


    else:
        return render_template('admin/admin_editdata.html',user=user)
    
    return render_template('admin/admin_editdata.html',user=user)

# 评论页
@admin.route('/commentContent')
def commentContent():
    # comments_1 = Comment.query.filter(Comment.article_id==1).all()
    # 用户确定，确定该用户文章，再确认该文章评论
    user = g.user
    comments_self = Article.query.filter(Article.user_id==user.id).all()
    comments_else = {}
    for i in comments_self:
        comments_all = Comment.query.filter(Comment.article_id==i.id).all()
        if len(comments_all)>0:
            comments_else[i] = comments_all

    print(comments_else)

    return render_template('admin/comment.html',comments_else=comments_else,user=user)



# 在视图函数钱执行的钩子函数
@admin.before_request
def my_before_request():
    user_id = session.get('user_id')
    if user_id:
        user = User.query.filter(User.id==user_id).first()
        if user:
            g.user = user


# 可以判断显示登录状态，不登录的状态一直执行
@admin.context_processor
def my_context_processor():
    if hasattr(g,'user'):
        return {'user':g.user}
    return {}

bokeItem/views/edit.py
from flask import Flask, Blueprint,render_template,request,redirect, url_for, session, g
from flask_sqlalchemy import SQLAlchemy
from config import*
from functools import wraps
from datetime import datetime
from sqlalchemy import or_
from werkzeug.security import generate_password_hash,check_password_hash
from app import db,Article,User
from random import random ,randint

edit = Blueprint('edit',__name__)


# 登录限制的装饰器
def login_required(func):
    @wraps(func)
    def wrapper(*args,**kwargs):
        # 如果登录状态，则可以执行访问
        if session.get('user_id'):
            return func(*args,**kwargs)
        else:
            # 否则直接跳转到登录页面
            return redirect(url_for('login.login_index'))
    return wrapper


# 编辑发布文章页
@edit.route('/',methods = ['GET','POST'])
@login_required
def edit_article():
    if request.method == 'GET':
        return render_template('edit/contact.html')
        
    else:
        title = request.form.get('title')
        
        content = request.form.get('content')
        types = request.form.get('types')
        imager=request.files['imager']
        text1=request.form.get('text1')
        # basepath = os.path.dirname(os.path.dirname(__file__))
        # print(basepath)
        num = randint(1,100000000)
        
        imager.save('./static/imager/%d%s' % ( num,imager.filename))
        img= '/static/imager/%d%s' % ( num,imager.filename)
        user = g.user
        article = Article(title=title,content=text1,types=types,user_id=user.id,img=img)
        # 因为有外键所以要指明是哪个作者author，所以从session里取出user_id找出user赋予question的作者
        article.author = user
        # print(article.author)
        db.session.add(article)
        db.session.commit()
        return redirect(url_for('boke'))

# 在视图函数钱执行的钩子函数
@edit.before_request
def my_before_request():
    user_id = session.get('user_id')
    if user_id:
        user = User.query.filter(User.id==user_id).first()
        if user:
            g.user = user


# 可以判断显示登录状态，不登录的状态一直执行
@edit.context_processor
def my_context_processor():
    if hasattr(g,'user'):
        return {'user':g.user}
    return {}

bokeItem/views/login.py
from flask import Blueprint,Flask, render_template, request, redirect, url_for, session, g
from flask_sqlalchemy import SQLAlchemy
import time
from app import User,db,Article,Comment
login = Blueprint('login',__name__)
import hashlib

# 登录首页
@login.route('/',methods = [ 'GET','POST'] )
def login_index():
    if request.method == 'GET':
        return render_template('login_register/login.html')
    else:
        telephone = request.form.get('login-telephone')
        password = request.form.get('login-password')
        #对用户输入的密码进行加密
        hash = hashlib.md5(bytes('9385',encoding='utf-8'))#md5对象，md5不能反解，但是加密是固定的，就是关系是一一对应，所以有缺陷，可以被对撞出来
        hash.update(bytes(password,encoding='utf-8'))#要对哪个字符串进行加密，就放这里
        password = hash.hexdigest()
        #验证
        vcode= request.form.get('vcode')
        print(vcode)
        user = User.query.filter(User.telephone==telephone).first()
        if user and user.password==password:
            session['user_id'] = user.id
            session.permanent = True
            return redirect(url_for('boke'))
        else:
            # return redirect(url_for('login.login_index'))
            return render_template('login_register/login.1.html')

# 管理员登录页
@login.route('/login_gl',methods=['GET','POST'])
def login_gl_index():
    if request.method == 'GET':
        return render_template('login_register/login_gl.html')
    else:
        username = request.form.get('username')
        password = request.form.get('pw')
        #对用户输入的密码进行加密
        # md5对象，md5不能反解，但是加密是固定的，就是关系是一一对应，所以有缺陷，可以被对撞出来
        hash = hashlib.md5(bytes('9385', encoding='utf-8'))
        hash.update(bytes(password, encoding='utf-8'))  # 要对哪个字符串进行加密，就放这里
        password = hash.hexdigest()
        
        user = User.query.filter(User.id==1).first()        
        if user and user.password==password:
                session['user_id'] = user.id
                session.permanent = True
                return render_template('X-admin/index.html',user=user)
        else:
            return render_template('login_register/login_gl.html')
# 欢迎首页
@login.route('/welcome.html',methods=['GET','POST'])
def welcome():
    users = User.query.filter(User.id!=1).all()  
    articles = Article.query.filter().all()
    comments = Comment.query.filter().all()
    readcount = 0
    agreecount = 0
    for article in articles:
        readcount += article.readcount
        agreecount += article.agreecount
    return render_template('X-admin/welcome.html',users=users,articles=articles,comments=comments,readcount=readcount,agreecount=agreecount) 

# 成员列表页
@login.route('/member-list.html',methods=['GET','POST'])
def member_list():
    users = User.query.filter(User.id!=1).all()
    return render_template('X-admin/member-list.html',users=users) 

# 删除成员
@login.route('/member-list.html/<user_id>') 
def member_list_del(user_id):
    delete_users = User.query.filter(User.id==user_id).first()
    delete_users.online = 1
    db.session.add(delete_users)
    db.session.commit()
    time.sleep(2)
    return redirect(url_for('login.member_list'))   
# 恢复成员
@login.route('/member-del.html/<user_id>') 
def member_list_huihu(user_id):
    delete_users = User.query.filter(User.id==user_id).first()
    delete_users.online = 0
    db.session.add(delete_users)
    db.session.commit()
    time.sleep(2)
    return redirect(url_for('login.member_del'))

# 成员恢复页
@login.route('/member-del.html',methods=['GET','POST'])
def member_del():
    users = User.query.filter(User.id!=1).all()
    return render_template('X-admin/member-del.html',users=users) 

# 文章列表页
@login.route('/article-list.html',methods=['GET','POST'])
def article_list():
    articles = Article.query.filter().all()
    return render_template('X-admin/article-list.html',articles=articles)

# 删除文章
@login.route('/article-list.html/<article_id>') 
def article_list_del(article_id):
    delete_articles = Article.query.filter(Article.id==article_id).first()
    delete_articles.isexit = 1
    db.session.add(delete_articles)
    db.session.commit()
    time.sleep(2)
    return redirect(url_for('login.article_list'))
# 文章恢复
@login.route('/article-del.html/<article_id>') 
def article_del_huihu(article_id):
    delete_articles = Article.query.filter(Article.id==article_id).first()
    delete_articles.isexit = 0
    db.session.add(delete_articles)
    db.session.commit()
    time.sleep(2)
    return redirect(url_for('login.article_del'))

# 文章恢复页
@login.route('/article-del.html',methods=['GET','POST'])
def article_del():
    articles = Article.query.filter().all()
    return render_template('X-admin/article-del.html',articles=articles) 

# 评论页
@login.route('/order-list.html',methods=['GET','POST'])
def order_list():
    comments = Comment.query.filter().all()
    return render_template('X-admin/order-list.html',comments=comments) 
# 分类页
@login.route('/cate.html',methods=['GET','POST'])
def cate():
    articles = Article.query.filter().all()
    return render_template('X-admin/cate.html',articles=articles) 

# 审核页
@login.route('/check-list.html',methods=['GET','POST'])
def check_article():
    articles = Article.query.filter().all()
    return render_template('X-admin/check-list.html',articles=articles)
# 审核文章通过
@login.route('/check-list.html/<article_id>') 
def article_list_check(article_id):
    delete_articles = Article.query.filter(Article.id==article_id).first()
    delete_articles.isexit = 0
    db.session.add(delete_articles)
    db.session.commit()
    time.sleep(2)
    return redirect(url_for('login.check_article'))


# 注销跳转登录页
@login.route('/logout')
def logout():
    # session.pop('user_id')
    # del session['user_id']
    session.clear()
    return redirect(url_for('login.login_index'))

bokeItem/views/register.py
from flask import Blueprint,render_template,request, redirect,url_for
from app import User,db
register = Blueprint('register',__name__)
import hashlib

# 注册页
@register.route('/',methods=['GET','POST'])
def register_index():
    if request.method == 'GET':
        return render_template('login_register/register.html')
    else:
        telephone = request.form.get('register-telephone')
        username = request.form.get('register-username')
        password1 = request.form.get('register-password1')
        password2 = request.form.get('register-password2')
        print(password1)
        print(password2)
        user = User.query.filter(User.telephone == telephone).first()
        if user:
            return '该手机号已被注册'
        else:
            if password1 != password2:
                return '两次密码不相等，请核对后再填写'
            else:
                #存入数据库之前对密码进行加密
                hash = hashlib.md5(bytes('9385',encoding='utf-8'))#md5对象，md5不能反解，但是加密是固定的，就是关系是一一对应，所以有缺陷，可以被对撞出来
                hash.update(bytes(password1,encoding='utf-8'))#要对哪个字符串进行加密，就放这里
                # print(hash.hexdigest())
                password1 = hash.hexdigest()

                user = User(telephone=telephone,username=username,password=password1,img='https://ps.ssl.qhimg.com/sdmt/133_135_100/t01d63c6c44877e340b.jpg',online='0')
                db.session.add(user)
                db.session.commit()
                return redirect(url_for('login.login_index'))

bokeItem/templates/edit/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>发布平台</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">

    <!-- Bootstrap styles -->
    <link rel="stylesheet" href="../../static/css/edit/bootstrap.min.css">
  

    <!-- Font-Awesome -->
    <link rel="stylesheet" href="../../static/css/edit/font-awesome/css/font-awesome.min.css">

    <!-- Google Webfonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600|PT+Serif:400,400italic' rel='stylesheet' type='text/css'>

    <!-- Styles -->
  <link rel="stylesheet" href="../../static/css/edit/style1.css" id="theme-styles">
  <link href="../../static/js/edit/wangEditor.min.js" rel="stylesheet">

    <!--[if lt IE 9]>      
        <script src="../static/js/edit/vendor/google/html5-3.6-respond-1.1.0.min.js"></script>
    <![endif]-->
    
</head>
<body>
    <!-- <header> -->
        <!-- <div class="widewrapper masthead">
            <div class="container">
                <a href="index.html" id="logo">
                    <img src="../../static/img/edit/logo.png" alt="clean Blog">
                </a>

                <div id="mobile-nav-toggle" class="pull-right">
                    <a href="#" data-toggle="collapse" data-target=".clean-nav .navbar-collapse">
                        <i class="fa fa-bars"></i>
                    </a>
                </div>

                <nav class="pull-right clean-nav">
                    <div class="collapse navbar-collapse">
                        <ul class="nav nav-pills navbar-nav">
                          
                             <li>
                                <a href="index.html">Home</a>
                            </li>
                            <li>
                                <a href="about.html">About</a>
                            </li>
                            <li>
                                <a href="contact.html">Contact</a>
                            </li>                 
                        </ul>
                    </div>
                </nav>        

            </div>
        </div> -->

        <!-- <div class="widewrapper subheader">
            <div class="container">
                <div class="clean-breadcrumb">
                    <a href="#">Contact Me</a>
                </div>
                <div class="clean-searchbox">
                    <form action="#" method="get" accept-charset="utf-8">
                        
                        <input class="searchfield" id="searchbox" type="text" placeholder="Search">
                         <button class="searchbutton" type="submit">
                            <i class="fa fa-search"></i>
                        </button>
                    </form>
                </div>
            </div>
        </div> -->
        <nav class="navbar navbar-inverse">
            <div class="container">
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="{{url_for('boke')}}">首页 <span class="sr-only">(current)</span></a></li>
                        <li><a href="{{url_for('edit.edit_article')}}">发布</a></li>
                    </ul>
                    <form style='margin-top:12px;' class="navbar-form navbar-left" action="{{url_for('search')}}" method="GET">
                        <div class="form-group">
                            <input type="text" name="q" class="form-control" placeholder="Search">
                        </div>
                        <button type="submit" class="btn btn-default">查找</button>
                    </form>
                    <ul class="nav navbar-nav navbar-right">
                        {% if user %}
                        <li><a href="{{url_for('admin.admin_message')}}"> <img class="adminImg" src="{{user.img}}" />{{user.username}}</a></li>
                        <li style='margin-top:6px;'><a href="{{url_for('login.logout')}}">注销</a></li>
                        {% else %}
                        <li><a href="{{url_for('login.login_index')}}">登录</a></li>
                        <li><a href="{{url_for('register.register_index')}}">注册</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    
    
    <!-- </header> -->

    <div class="widewrapper main" style='background: url(../../img/edit/paopao.png) no-repeat;'>
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3 clean-superblock" id="contact">
                    <h2>发表文章</h2>
                    
                    <form action="" method="post" accept-charset="utf-8" class="contact-form" enctype="multipart/form-data">
                        <input type="text" name="title" id="contact-name" placeholder="请输入标题" class="form-control input-lg">
                        <!--<a href="javascript:;" class="a-upload form-control input-lg">-->
                        	<label id="b" class="col-sm-10 control-label" for='a'>请选择图片</label>
    						<input type="file" name="imager" id="a" hidden="hidden" style="display: none;">
						<!--</a>-->
                        <!--<input type="email" name="email" id="contact-email" placeholder="Email" class="form-control input-lg">-->
                       
                        <label id="lable1" class="col-sm-6 control-label">请选择文章类型</label>
						<div class="">
						    <select id="select1" class="form-control input-lg"  name="types">
						        <option>娱乐</option>
						        <option>军事</option>
						        <option>网络</option>
                                <option>技术</option>
                                <option>美食</option>
                                <option>医疗</option>
                                <option>旅游</option>
                                <option>摄影</option>
						    </select>
						</div>
                        <!--<textarea rows="10" name="content" id="contact-body" placeholder="请输入内容" class="form-control input-lg"></textarea>
                        <div class="buttons clearfix">
                            <button type="submit" class="btn btn-xlarge btn-clean-one">立即发表</button>
                        </div>                    -->
                        <!--<div id="editor" style="padding-top: 25px;">
					        <p>欢迎使用 <b>wangEditor</b> 富文本编辑器</p>
					    </div>-->
					    <div class="">
                            <input type="text" id='content' placeholder="提示信息" class="col-sm-10" name='content' hidden />
                            <input type="text" id='text1' placeholder="提示信息" class="col-sm-10" name='text1' hidden />
                            
                            
                            <div id="editor" style="padding-top: 25px ;text-index:2em">
                                <p>欢迎使用 <b>wangEditor</b> 富文本编辑器</p>
                            </div>
                            
                        </div>
                        <button type="submit" class="btn btn-xlarge btn-clean-one">立即发表</button>
                    </form>
                </div>
            </div>        
        </div>
    </div>

   <!--<footer>
        <div class="widewrapper footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 footer-widget">
                        <h3> <i class="fa fa-user"></i>About</h3>

                       <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab animi laboriosam nostrum consequatur fugiat at, labore praesentium modi, quasi dolorum debitis reiciendis facilis, dolor saepe sint nemo, earum molestias quas.</p>
                       <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorum, error aspernatur assumenda quae eveniet.</p>
                    </div>

                    <div class="col-md-4 footer-widget">
                        <h3> <i class="fa fa-pencil"></i> Recent Post</h3>
                        <ul class="clean-list">
                            <li><a href="">Clean - Responsive HTML5 Template</a></li>
                            <li><a href="">Responsive Pricing Table</a></li>
                            <li><a href="">Yellow HTML5 Template</a></li>
                        </ul>
                    </div>

                    <div class="col-md-4 footer-widget">
                        <h3> <i class="fa fa-envelope"></i>Contact Me</h3>

                        <p>Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil fugiat, cupiditate veritatis excepturi tempore explicabo.</p>
                         <div class="footer-widget-icon">
                            <i class="fa fa-facebook"></i><i class="fa fa-twitter"></i><i class="fa fa-google"></i>
                        </div>
                    </div>
                   
                </div>
            </div>
        </div>
        <div class="widewrapper copyright">
                Copyright &copy; 2017.Company name All rights reserved.<a target="_blank" href="http://sc.chinaz.com/moban/">&#x7F51;&#x9875;&#x6A21;&#x677F;</a>
        </div>
    </footer>-->
    
    <script src="../../static/js/edit/jquery.min.js"></script>
    <script src="../../static/js/edit/bootstrap.min.js"></script>
    <script src="../../static/js/edit/modernizr.js"></script>

	<script type="text/javascript" src="../../static/js/edit/wangEditor.min.js"></script>
    
    <script>
        var E = window.wangEditor
        var editor = new E('#editor')
        var $text1 = $('#text1')
        // 或者 var editor = new E( document.getElementById('editor') )

        editor.customConfig.onchange = function (html) {
        // 监控变化，同步更新到 textarea
            $('#content').val(html)
            $text1.val(editor.txt.text())
            
        }
        
        editor.create()
        //设置内容
        editor.txt.html('<p>请写你的文章</p>')
        

    </script>

</body>
</html>