bokeItem/views/login.py
from flask import Blueprint,Flask, render_template, request, redirect, url_for, session, g
from flask_sqlalchemy import SQLAlchemy
import time
from app import User,db,Article,Comment
login = Blueprint('login',__name__)
import hashlib

# 登录首页
@login.route('/',methods = [ 'GET','POST'] )
def login_index():
    if request.method == 'GET':
        return render_template('login_register/login.html')
    else:
        telephone = request.form.get('login-telephone')
        password = request.form.get('login-password')
        #对用户输入的密码进行加密
        hash = hashlib.md5(bytes('9385',encoding='utf-8'))#md5对象，md5不能反解，但是加密是固定的，就是关系是一一对应，所以有缺陷，可以被对撞出来
        hash.update(bytes(password,encoding='utf-8'))#要对哪个字符串进行加密，就放这里
        password = hash.hexdigest()
        #验证
        vcode= request.form.get('vcode')
        print(vcode)
        user = User.query.filter(User.telephone==telephone).first()
        if user and user.password==password:
            session['user_id'] = user.id
            session.permanent = True
            return redirect(url_for('boke'))
        else:
            # return redirect(url_for('login.login_index'))
            return render_template('login_register/login.1.html')

# 管理员登录页
@login.route('/login_gl',methods=['GET','POST'])
def login_gl_index():
    if request.method == 'GET':
        return render_template('login_register/login_gl.html')
    else:
        username = request.form.get('username')
        password = request.form.get('pw')
        #对用户输入的密码进行加密
        # md5对象，md5不能反解，但是加密是固定的，就是关系是一一对应，所以有缺陷，可以被对撞出来
        hash = hashlib.md5(bytes('9385', encoding='utf-8'))
        hash.update(bytes(password, encoding='utf-8'))  # 要对哪个字符串进行加密，就放这里
        password = hash.hexdigest()
        
        user = User.query.filter(User.id==1).first()        
        if user and user.password==password:
                session['user_id'] = user.id
                session.permanent = True
                return render_template('X-admin/index.html',user=user)
        else:
            return render_template('login_register/login_gl.html')
# 欢迎首页
@login.route('/welcome.html',methods=['GET','POST'])
def welcome():
    users = User.query.filter(User.id!=1).all()  
    articles = Article.query.filter().all()
    comments = Comment.query.filter().all()
    readcount = 0
    agreecount = 0
    for article in articles:
        readcount += article.readcount
        agreecount += article.agreecount
    return render_template('X-admin/welcome.html',users=users,articles=articles,comments=comments,readcount=readcount,agreecount=agreecount) 

# 成员列表页
@login.route('/member-list.html',methods=['GET','POST'])
def member_list():
    users = User.query.filter(User.id!=1).all()
    return render_template('X-admin/member-list.html',users=users) 

# 删除成员
@login.route('/member-list.html/<user_id>') 
def member_list_del(user_id):
    delete_users = User.query.filter(User.id==user_id).first()
    delete_users.online = 1
    db.session.add(delete_users)
    db.session.commit()
    time.sleep(2)
    return redirect(url_for('login.member_list'))   
# 恢复成员
@login.route('/member-del.html/<user_id>') 
def member_list_huihu(user_id):
    delete_users = User.query.filter(User.id==user_id).first()
    delete_users.online = 0
    db.session.add(delete_users)
    db.session.commit()
    time.sleep(2)
    return redirect(url_for('login.member_del'))

# 成员恢复页
@login.route('/member-del.html',methods=['GET','POST'])
def member_del():
    users = User.query.filter(User.id!=1).all()
    return render_template('X-admin/member-del.html',users=users) 

# 文章列表页
@login.route('/article-list.html',methods=['GET','POST'])
def article_list():
    articles = Article.query.filter().all()
    return render_template('X-admin/article-list.html',articles=articles)

# 删除文章
@login.route('/article-list.html/<article_id>') 
def article_list_del(article_id):
    delete_articles = Article.query.filter(Article.id==article_id).first()
    delete_articles.isexit = 1
    db.session.add(delete_articles)
    db.session.commit()
    time.sleep(2)
    return redirect(url_for('login.article_list'))
# 文章恢复
@login.route('/article-del.html/<article_id>') 
def article_del_huihu(article_id):
    delete_articles = Article.query.filter(Article.id==article_id).first()
    delete_articles.isexit = 0
    db.session.add(delete_articles)
    db.session.commit()
    time.sleep(2)
    return redirect(url_for('login.article_del'))

# 文章恢复页
@login.route('/article-del.html',methods=['GET','POST'])
def article_del():
    articles = Article.query.filter().all()
    return render_template('X-admin/article-del.html',articles=articles) 

# 评论页
@login.route('/order-list.html',methods=['GET','POST'])
def order_list():
    comments = Comment.query.filter().all()
    return render_template('X-admin/order-list.html',comments=comments) 
# 分类页
@login.route('/cate.html',methods=['GET','POST'])
def cate():
    articles = Article.query.filter().all()
    return render_template('X-admin/cate.html',articles=articles) 

# 审核页
@login.route('/check-list.html',methods=['GET','POST'])
def check_article():
    articles = Article.query.filter().all()
    return render_template('X-admin/check-list.html',articles=articles)
# 审核文章通过
@login.route('/check-list.html/<article_id>') 
def article_list_check(article_id):
    delete_articles = Article.query.filter(Article.id==article_id).first()
    delete_articles.isexit = 0
    db.session.add(delete_articles)
    db.session.commit()
    time.sleep(2)
    return redirect(url_for('login.check_article'))


# 注销跳转登录页
@login.route('/logout')
def logout():
    # session.pop('user_id')
    # del session['user_id']
    session.clear()
    return redirect(url_for('login.login_index'))

bokeItem/views/register.py
from flask import Blueprint,render_template,request, redirect,url_for
from app import User,db
register = Blueprint('register',__name__)
import hashlib

# 注册页
@register.route('/',methods=['GET','POST'])
def register_index():
    if request.method == 'GET':
        return render_template('login_register/register.html')
    else:
        telephone = request.form.get('register-telephone')
        username = request.form.get('register-username')
        password1 = request.form.get('register-password1')
        password2 = request.form.get('register-password2')
        print(password1)
        print(password2)
        user = User.query.filter(User.telephone == telephone).first()
        if user:
            return '该手机号已被注册'
        else:
            if password1 != password2:
                return '两次密码不相等，请核对后再填写'
            else:
                #存入数据库之前对密码进行加密
                hash = hashlib.md5(bytes('9385',encoding='utf-8'))#md5对象，md5不能反解，但是加密是固定的，就是关系是一一对应，所以有缺陷，可以被对撞出来
                hash.update(bytes(password1,encoding='utf-8'))#要对哪个字符串进行加密，就放这里
                # print(hash.hexdigest())
                password1 = hash.hexdigest()

                user = User(telephone=telephone,username=username,password=password1,img='https://ps.ssl.qhimg.com/sdmt/133_135_100/t01d63c6c44877e340b.jpg',online='0')
                db.session.add(user)
                db.session.commit()
                return redirect(url_for('login.login_index'))

bokeItem/templates/login_register/login.1.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport"
	content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
<title>登录</title>
<link rel="stylesheet" href="../../static/css/login/normalize.css">
<link rel="stylesheet" href="../../static/css/login/login.css">
<link rel="stylesheet" href="../../static/css/login/sign-up-login.css">
<link rel="stylesheet" type="text/css" href="http://cdn.bootcss.com/font-awesome/4.6.0/css/font-awesome.min.css">
<link rel="stylesheet" href="../../static/css/login/inputEffect.css" />
<link rel="stylesheet" href="../../static/css/login/tooltips.css" />
<link rel="stylesheet" href="../../static/css/login/spop.min.css" />
<link rel="stylesheet" href="../../static/css/login/yanzheng.css" />

<script src="../../static/js/login/jquery.min.js"></script>
<!-- <script src="../../static/js/login/snow.js"></script> -->
<script src="../../static/js/login/jquery.pure.tooltips.js"></script>
<script src="../../static/js/login/spop.min.js"></script>
<script src="../../static/js/login/login.js"></script>
<script src="../../static/js/login/yanzheng.js"></script>
<style type="text/css">
html{
	width: 100%; 
	height: 100%;
}

body{

	background-repeat: no-repeat;

	background-position: center center #2D0F0F;

	background-color: #00BDDC;

	background-image: url(../../static/img/login/beijing.jpg);

	background-size: 100% 100%;

}

.snow-container { 
	position: fixed; 
	top: 0; 
	left: 0; 
	width: 100%; 
	height: 100%; 
	pointer-events: none; 
	z-index: 100001; 
}

</style>
</head>
<body>
	<!-- 雪花背景 -->
	<div class="snow-container"></div>
	<!-- 登录控件 -->
	<div id="login">
		<input id="tab-1" type="radio" name="tab" class="sign-in hidden" checked />
		<input id="tab-2" type="radio" name="tab" class="sign-up hidden" />
		<input id="tab-3" type="radio" name="tab" class="sign-out hidden" />
		<div class="wrapper">
			<a id="fanhui" href='{{url_for("boke")}}'>返回首页</a>
			<!-- 登录页面 -->
			<div class="login sign-in-htm">
				<form class="container offset1 loginform"  onsubmit="return check()" action='' method="POST">
					<!-- 猫头鹰控件 -->
					<div id="owl-login" class="login-owl">
						<div class="hand"></div>
						<div class="hand hand-r"></div>
						<div class="arms">
							<div class="arm"></div>
							<div class="arm arm-r"></div>
						</div>
					</div>
					<div class="pad input-container">
						<div>登录</div>
						<section class="content">
						
							<span class="input input--hideo">
								<input class="input__field input__field--hideo" type="text" id="login-username" name="login-telephone"
									autocomplete="off" placeholder="请输入手机号" tabindex="1" maxlength="15" />
								<label class="input__label input__label--hideo" for="login-username">
									<i class="fa fa-fw fa-user icon icon--hideo"></i>
									<span class="input__label-content input__label-content--hideo"></span>
								</label>
							</span>
							<span class="input input--hideo">
								<input class="input__field input__field--hideo" type="password" id="login-password" name="login-password" placeholder="请输入密码" tabindex="2" maxlength="15"/>
								<label class="input__label input__label--hideo" for="login-password">
									<i class="fa fa-fw fa-lock icon icon--hideo"></i>
									<span class="input__label-content input__label-content--hideo"></span>
								</label>
							</span>

							<span class="input input--hideo" id="login-yanzheng">
								
								<input type="text" placeholder="验证码" id="vcode" name='vcode' value="验证码" onfocus="this.value=''" onblur="if(this.value=='')this.value='验证码'"/>
								<span id="code" title="看不清？换一张～" onclick=changeImg()></span>
							</span>
							<span class="false">账号或密码不正确</span>



						</section>
						
					</span>

					<div class="form-actions">
						<a tabindex="4" class="btn pull-left btn-link text-muted" href='{{url_for("login.login_gl_index")}}'>管理员登录</a>
						<a tabindex="5" class="btn btn-link text-muted" href='{{url_for("register.register_index")}}'>注册</a> 
						<!-- href="register.html" -->
						<input class="btn btn-primary" type="submit" tabindex="3" value="登录" 
							style="color:white;"/>
					</div>
				</form>
			</div>
			
		</div>
	</div>

	<script>
		changeImg()
	</script>
</body>
</html>

bokeItem/templates/login_register/login.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport"
	content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
<title>登录</title>
<link rel="stylesheet" href="../../static/css/login/normalize.css">
<link rel="stylesheet" href="../../static/css/login/login.css">
<link rel="stylesheet" href="../../static/css/login/sign-up-login.css">
<link rel="stylesheet" type="text/css" href="http://cdn.bootcss.com/font-awesome/4.6.0/css/font-awesome.min.css">
<link rel="stylesheet" href="../../static/css/login/inputEffect.css" />
<link rel="stylesheet" href="../../static/css/login/tooltips.css" />
<link rel="stylesheet" href="../../static/css/login/spop.min.css" />
<link rel="stylesheet" href="../../static/css/login/yanzheng.css" />

<script src="../../static/js/login/jquery.min.js"></script>
<!-- <script src="../../static/js/login/snow.js"></script> -->
<script src="../../static/js/login/jquery.pure.tooltips.js"></script>
<script src="../../static/js/login/spop.min.js"></script>
<script src="../../static/js/login/login.js"></script>
<script src="../../static/js/login/yanzheng.js"></script>
<style type="text/css">
html{
	width: 100%; 
	height: 100%;
}

body{

	background-repeat: no-repeat;

	background-position: center center #2D0F0F;

	background-color: #00BDDC;

	background-image: url(../../static/img/login/beijing.jpg);

	background-size: 100% 100%;

}

.snow-container { 
	position: fixed; 
	top: 0; 
	left: 0; 
	width: 100%; 
	height: 100%; 
	pointer-events: none; 
	z-index: 100001; 
}

</style>
</head>
<body>
	<!-- 雪花背景 -->
	<div class="snow-container"></div>
	<!-- 登录控件 -->
	<div id="login">
		<input id="tab-1" type="radio" name="tab" class="sign-in hidden" checked />
		<input id="tab-2" type="radio" name="tab" class="sign-up hidden" />
		<input id="tab-3" type="radio" name="tab" class="sign-out hidden" />
		<div class="wrapper">
			<a id="fanhui" href='{{url_for("boke")}}'>返回首页</a>
			<!-- 登录页面 -->
			<div class="login sign-in-htm">
				<form class="container offset1 loginform"  onsubmit="return check()" action='' method="POST">
					<!-- 猫头鹰控件 -->
					<div id="owl-login" class="login-owl">
						<div class="hand"></div>
						<div class="hand hand-r"></div>
						<div class="arms">
							<div class="arm"></div>
							<div class="arm arm-r"></div>
						</div>
					</div>
					<div class="pad input-container">
						<div>登录</div>
						<section class="content">
						
							<span class="input input--hideo">
								<input class="input__field input__field--hideo" type="text" id="login-username" name="login-telephone"
									autocomplete="off" placeholder="请输入手机号" tabindex="1" maxlength="15" />
								<label class="input__label input__label--hideo" for="login-username">
									<i class="fa fa-fw fa-user icon icon--hideo"></i>
									<span class="input__label-content input__label-content--hideo"></span>
								</label>
							</span>
							<span class="input input--hideo">
								<input class="input__field input__field--hideo" type="password" id="login-password" name="login-password" placeholder="请输入密码" tabindex="2" maxlength="15"/>
								<label class="input__label input__label--hideo" for="login-password">
									<i class="fa fa-fw fa-lock icon icon--hideo"></i>
									<span class="input__label-content input__label-content--hideo"></span>
								</label>
							</span>

							<span class="input input--hideo" id="login-yanzheng">
								
								<input type="text" placeholder="验证码" id="vcode" name='vcode' value="验证码" onfocus="this.value=''" onblur="if(this.value=='')this.value='验证码'"/>
								<span id="code" title="看不清？换一张～" onclick=changeImg()></span>
							</span>



						</section>
						
					</span>

					<div class="form-actions">
						<a tabindex="4" class="btn pull-left btn-link text-muted" href='{{url_for("login.login_gl_index")}}'>管理员登录</a>
						<a tabindex="5" class="btn btn-link text-muted" href='{{url_for("register.register_index")}}'>注册</a> 
						<!-- href="register.html" -->
						<input class="btn btn-primary" type="submit" tabindex="3" value="登录" 
							style="color:white;"/>
					</div>
				</form>
			</div>
			
		</div>
	</div>

	<script>
		changeImg()
	</script>
</body>
</html>

bokeItem/templates/login_register/login_gl.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport"
	content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
<title>登录注册</title>
<link rel="stylesheet" href="../../static/css/login/normalize.css">
<link rel="stylesheet" href="../../static/css/login/login.css">
<link rel="stylesheet" href="../../static/css/login/sign-up-login.css">
<link rel="stylesheet" type="text/css" href="http://cdn.bootcss.com/font-awesome/4.6.0/css/font-awesome.min.css">
<link rel="stylesheet" href="../../static/css/login/inputEffect.css" />
<link rel="stylesheet" href="../../static/css/login/tooltips.css" />
<link rel="stylesheet" href="../../static/css/login/spop.min.css" />

<script src="../../static/js/login/jquery.min.js"></script>
<!-- <script src="../../static/js/login/snow.js"></script> -->
<script src="../../static/js/login/jquery.pure.tooltips.js"></script>
<script src="../../static/js/login/spop.min.js"></script>
<script src="../../static/js/login/login.js"></script>

<script>	
	
	//普通用户登录
	function login(){
		var username = $("#login-username").val(),
			password = $("#login-password").val(),
			validatecode = null,
			flag = false;
		//判断用户名密码是否为空
		if(username == ""){
			$.pt({
        		target: $("#login-username"),
        		position: 'r',
        		align: 't',
        		width: 'auto',
        		height: 'auto',
        		content:"用户名不能为空"
        	});
			flag = true;
		}
		if(password == ""){
			$.pt({
        		target: $("#login-password"),
        		position: 'r',
        		align: 't',
        		width: 'auto',
        		height: 'auto',
        		content:"密码不能为空"
        	});
			flag = true;
		}else{
			if(password != repassword){
				$.pt({
	        		target: $("#register-repassword"),
	        		position: 'r',
	        		align: 't',
	        		width: 'auto',
	        		height: 'auto',
	        		content:"两次输入的密码不一致"
	        	});
				flag = true;
			}
		}
		//用户名只能是15位以下的字母或数字
		var regExp = new RegExp("^[a-zA-Z0-9_]{1,15}$");
		if(!regExp.test(username)){
			$.pt({
        		target: $("#login-username"),
        		position: 'r',
        		align: 't',
        		width: 'auto',
        		height: 'auto',
        		content:"用户名必须为15位以下的字母或数字"
        	});
			flag = true;
		}
		
		if(flag){
			return false;
		}else{//登录
			//调用后台登录验证的方法
			alert('登录成功');
			return false;
		}
	}
	
	
	
		
	
	

	
</script>
<style type="text/css">
html{
	width: 100%; 
	height: 100%;
}

body{

	background-repeat: no-repeat;

	background-position: center center #2D0F0F;

	background-color: #00BDDC;

	background-image: url(../../static/img/login/DB.jpg);

	background-size: 100% 100%;

}

.snow-container { 
	position: fixed; 
	top: 0; 
	left: 0; 
	width: 100%; 
	height: 100%; 
	pointer-events: none; 
	z-index: 100001; 
}

</style>
</head>
<body>
	<!-- 雪花背景 -->
	<div class="snow-container"></div>
	<!-- 登录控件 -->
	<div id="login">
		<input id="tab-1" type="radio" name="tab" class="sign-in hidden" checked />
		<input id="tab-2" type="radio" name="tab" class="sign-up hidden" />
		<input id="tab-3" type="radio" name="tab" class="sign-out hidden" />
		<div class="wrapper">
			<a id="fanhui" href='{{url_for("boke")}}'>返回首页</a>
			<!-- 登录页面 -->
			<div class="login sign-in-htm">
				<form class="container offset1 loginform" method="POST">
					<!-- 猫头鹰控件 -->
					<div id="owl-login" class="login-owl">
						<div class="hand"></div>
						<div class="hand hand-r"></div>
						<div class="arms">
							<div class="arm"></div>
							<div class="arm arm-r"></div>
						</div>
					</div>
					<div class="pad input-container">
						<div>管理员登录</div>
						<section class="content">
							<span class="input input--hideo">
								<input class="input__field input__field--hideo" name="username" type="text" id="forget-username" autocomplete="off" placeholder="请输入用户名"/>
								<label class="input__label input__label--hideo" for="forget-username">
									<i class="fa fa-fw fa-user icon icon--hideo"></i>
									<span class="input__label-content input__label-content--hideo"></span>
								</label>
							</span>
							<span class="input input--hideo">
								<input class="input__field input__field--hideo" name="pw" type="password" id="forget-password" placeholder="请输入密码" tabindex="2" maxlength="15"/>
								<label class="input__label input__label--hideo" for="login-password">
									<i class="fa fa-fw fa-lock icon icon--hideo"></i>
									<span class="input__label-content input__label-content--hideo"></span>
								</label>
							</span>
							
						</section>
					</div>
					<div class="form-actions">
						<a class="btn pull-left btn-link text-muted" href='{{url_for("login.login_index")}}'href="login.html">返回登录</a>
						<input class="btn btn-primary" type="submit" onClick="forget()" value="管理员登录" 
							style="color:white;"/>
					</div>
				</form>
			</div>
			
		</div>
	</div>
</body>
</html>

bokeItem/templates/login_register/register.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport"
	content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
<title>注册</title>
<link rel="stylesheet" href="../../static/css/login/normalize.css">
<link rel="stylesheet" href="../../static/css/login/login.css">
<link rel="stylesheet" href="../../static/css/login/sign-up-login.css">
<link rel="stylesheet" type="text/css" href="http://cdn.bootcss.com/font-awesome/4.6.0/css/font-awesome.min.css">
<link rel="stylesheet" href="../../static/css/login/inputEffect.css" />
<link rel="stylesheet" href="../../static/css/login/tooltips.css" />
<link rel="stylesheet" href="../../static/css/login/spop.min.css" />

<script src="../../static/js/login/jquery.min.js"></script>
<!-- <script src="../../static/js/login/snow.js"></script> -->
<script src="../../static/js/login/jquery.pure.tooltips.js"></script>
<script src="../../static/js/login/spop.min.js"></script>
<script src="../../static/js/login/login.js"></script>

<style type="text/css">
html{
	width: 100%; 
	height: 100%;
}

body{

	background-repeat: no-repeat;

	background-position: center center #2D0F0F;

	background-color: #00BDDC;

	background-image: url(../../static/img/login/flower.jpg);

	background-size: 100% 100%;

}

.snow-container { 
	position: fixed; 
	top: 0; 
	left: 0; 
	width: 100%; 
	height: 100%; 
	pointer-events: none; 
	z-index: 100001; 
}

</style>
</head>
<body>
	<!-- 雪花背景 -->
	<div class="snow-container"></div>
	<!-- 登录控件 -->
	<div id="login">
		<input id="tab-1" type="radio" name="tab" class="sign-in hidden" checked />
		<input id="tab-2" type="radio" name="tab" class="sign-up hidden" />
		<input id="tab-3" type="radio" name="tab" class="sign-out hidden" />
		<div class="wrapper">
			<a id="fanhui" href='{{url_for("boke")}}'>返回首页</a>
			<!-- 登录页面 -->
			<div class="login sign-in-htm">
				<form class="container offset1 loginform" action='' method='POST'>
					<!-- 猫头鹰控件 -->
					<div id="owl-login" class="login-owl">
						<div class="hand"></div>
						<div class="hand hand-r"></div>
						<div class="arms">
							<div class="arm"></div>
							<div class="arm arm-r"></div>
						</div>
					</div>
					<div class="pad input-container">
						<div>注册</div>
						<section class="content">
							<span class="input input--hideo">
								<input class="input__field input__field--hideo" type="text" id="register-telephone" name='register-telephone'
									autocomplete="off" placeholder="请输入手机号" maxlength="15"/>
								<label class="input__label input__label--hideo" for="register-telephone">
									<i class="fa fa-fw fa-user icon icon--hideo"></i>
									<span class="input__label-content input__label-content--hideo"></span>
								</label>
							</span>
							<span class="input input--hideo">
								<input class="input__field input__field--hideo" type="text" id="register-username" name='register-username'
									autocomplete="off" placeholder="请输入用户名" maxlength="15"/>
								<label class="input__label input__label--hideo" for="register-username">
									<i class="fa fa-fw fa-user icon icon--hideo"></i>
									<span class="input__label-content input__label-content--hideo"></span>
								</label>
							</span>
							<span class="input input--hideo">
								<input class="input__field input__field--hideo" type="password" id="register-password" name='register-password1' placeholder="请输入密码" tabindex="2" maxlength="15"/>
								<label class="input__label input__label--hideo" for="register-password">
									<i class="fa fa-fw fa-lock icon icon--hideo"></i>
									<span class="input__label-content input__label-content--hideo"></span>
								</label>
							</span>
							<span class="input input--hideo">
								<input class="input__field input__field--hideo" type="password" id="register-repassword" name='register-password2' placeholder="请确认密码" tabindex="2" maxlength="15"/>
								<label class="input__label input__label--hideo" for="register-repassword">
									<i class="fa fa-fw fa-lock icon icon--hideo"></i>
									<span class="input__label-content input__label-content--hideo"></span>
								</label>
							</span>
							<span class="input input--hideo">
								
								<label class="input__label input__label--hideo" for="register-code">
									<i class="fa fa-fw fa-wifi icon icon--hideo"></i>
									<span class="input__label-content input__label-content--hideo"></span>
								</label>
							</span>
						</section>
					</div>
					<!--注册页面-->
					<div class="form-actions">
						<a class="btn pull-left btn-link text-muted" href='{{url_for("login.login_index")}}'href="login.html">返回登录</a>
						<input class="btn btn-primary" type="submit"  value="注册" style="color:white;"/>
					</div>
				</form>
			</div>
			
		</div>
	</div>
</body>
</html>